### ISSUE TITLE
El código no trabaja bien

### ISSUE THREAD

**Issue by AdolfoGrossoGamboa** [cristobalvch/Jobs-Chile#1]
Hola amigo, cómo estás, intenté correr el código en mi laptop, y corrió, pero me da como resultado cero, tanto con el buscador de trabajo de chile, como con el de Perú.
No sé exactamente donde está el problema, ya que no arroja error, sólo que no hace bien la búsqueda. Podrías ayudarme a solucionarlo, por favor, muchas gracias.

Me arroja esto:
webscraping_jobs("ingeniero", 10)
Running Web Scraping...
Web Scraping Finished!
Total Job Offers Extracted: 0

**Comment by cristobalvch** [comment]
Hola estimado!
El codigo no esta siendo mantenido actualmente, y debido a que se desarrollo en 2020, la pagina web tiene que haber tenido cambios. por lo que para solucionar los errores debes cambiar las rutas de los elementos (div, h, p, a, etc) del codigo html de la pagina web.

Saludos!!
