### ISSUE TITLE
Hola como estás, una consulta 

### ISSUE THREAD

**Issue by KevinMarcos26** [cristobalvch/Jobs-Chile#3]
Hello como estás, muchas gracias por este tremendo proyecto,  con algunos cambios he logrado traerme algunas ofertas laborales,  pero en 2024, sabes como hacer para traerme los datos de Salario y tipo de trabajo si es Remoto o Presencial de la página de computrabajo ??? Seguro debe haber habido cambios y no me las estoy pudiendo traer?? Agradezco mucho cualquier información al respecto.

**Comment by cristobalvch** [comment]
Hola que tal! me alegra que hayas podido reutilizar el codigo para hacer tu webscraping!. Cuando lo desarrolle estaba recien aprendiendo a hacer webscraping por lo que  lo siento si esta muy desordenado o complejo de entender jaja.

viendo el codigo html de la pagina, el contenido de tipo de trabajo para saber si es presencial o remoto esta dentro de un span  de clase ''icon i_company mrB', por lo que podrias buscar por esa clase o bien usar algun regex para encontrar las clases que contengan la palabra company.

Para el salario es lo mismo pero con el tag span de clase  icon i_money mrB

espero te ayude en algo!

saludos

**Comment by KevinMarcos26** [comment]
Muchísimas gracias estimado, super amable en responder,  y tremendo código te has mandado, como 4 años después y es súper reutilizable jaj. Un saludo cordial y muchísimas gracias.
